version: '3'

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'

includes:
  contents:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.2'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'contents'
      SPHINX_SOURCE_DIR: ''
      SPHINX_OUTPUT_DIR: '../build'
      SPHINX_DEFAULT_BUILDER: 'mini18n-dirhtml'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'aqua install -l'
      - 'uv sync --frozen --all-extras'
      - 'lefthook install'
  verify:
    desc: 'Verify environment by all procs'
    cmds:
      - 'lefthook run pre-commit --all-files'
      - '{{.RUN_PYTHON}} pytest'
      - task: 'docs:intl'
      - task: 'docs:build-linkcheck'
      - task: 'docs:build-dirhtml'
      - 'uv build'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-extras' # To write out as lock-file
